package main

import (
	"crypto/ed25519"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/random1st/skilltrust/attest"
	"github.com/random1st/skilltrust/catalog"
	"github.com/random1st/skilltrust/enrollment"
	"github.com/random1st/skilltrust/internal/marketplace"
	"github.com/random1st/skilltrust/internal/source"
)

const marketplaceUsage = `Usage: skillctl marketplace <subcommand> [flags]

  sign         sign the plugins a Claude Code marketplace repository owns
  prepare-notary  write the GitHub Actions workflow that submits signed catalogs with OIDC
  countersign  add a second signature to an index somebody else signed
  verify  check installed plugins against the marketplace's signature

`

const generatedWorkflowMarker = "# Generated by skillctl marketplace prepare-notary. Re-run this command to refresh it."

func runMarketplace(args []string) int {
	if len(args) == 0 {
		fmt.Fprint(os.Stderr, marketplaceUsage)
		return exitUsage
	}
	switch args[0] {
	case "sign":
		return runMarketplaceSign(args[1:])
	case "prepare-notary":
		return runMarketplacePrepareNotary(args[1:])
	case "countersign":
		return runMarketplaceCountersign(args[1:])
	case "verify":
		return runMarketplaceVerify(args[1:])
	default:
		fmt.Fprintf(os.Stderr, "unknown marketplace subcommand %q\n\n%s", args[0], marketplaceUsage)
		return exitUsage
	}
}

// runMarketplaceSign signs what a Claude Code marketplace already publishes.
//
// The catalog is not a second file an organisation has to maintain: it is their existing
// marketplace.json, digested plugin by plugin and signed beside it. A separate catalog would
// drift from the real one, and the drift would be invisible until the day it mattered.
func runMarketplaceSign(args []string) int {
	flags := flag.NewFlagSet("marketplace sign", flag.ContinueOnError)
	flags.Usage = func() {
		fmt.Fprintf(flags.Output(), "Usage: skillctl marketplace sign [flags] [repository]\n\n"+
			"Digests every plugin the marketplace owns and signs the result into %s,\n"+
			"beside the marketplace it describes. Plugins hosted elsewhere are reported,\n"+
			"not signed: their bytes come from somewhere this publisher does not control.\n\n"+
			"Exit codes: %d signed, %d error.\n\nFlags:\n",
			CatalogFileName, exitClean, exitUsage)
		flags.PrintDefaults()
	}

	keyPath := flags.String("key", defaultSigningKey(), "signing key")
	validFor := flags.Duration("valid-for", 7*24*time.Hour,
		"how long consumers may keep using this signature before refreshing")
	if err := parseArgs(flags, args); err != nil {
		return exitUsage
	}
	repository := flags.Arg(0)
	if repository == "" {
		repository = "."
	}
	repository, err := filepath.Abs(repository)
	if err != nil {
		return fail(err)
	}

	manifest, err := marketplace.Load(repository)
	if err != nil {
		return fail(err)
	}
	coverage, err := marketplace.Plan(repository, manifest)
	if err != nil {
		return fail(err)
	}
	if len(coverage.Signed) == 0 {
		fmt.Fprintf(os.Stderr, "skillctl: %s owns no plugins this key can sign\n", manifest.Name)
		return exitUsage
	}

	key, err := attest.LoadPrivateKey(*keyPath)
	if err != nil {
		return fail(err)
	}

	now := time.Now().UTC()
	snapshot := catalog.Snapshot{
		Version: catalog.SnapshotVersion, Name: manifest.Name, Sequence: 1,
		IssuedAt: now, ValidUntil: now.Add(*validFor), Skills: coverage.Signed,
	}

	indexPath := filepath.Join(repository, CatalogFileName)
	if existing, err := attest.LoadEnvelope(indexPath); err == nil {
		previous, _, err := catalog.Open(existing,
			attest.NewTrustedKeys(key.Public().(ed25519.PublicKey)))
		if err != nil {
			fmt.Fprintf(os.Stderr,
				"skillctl: refusing to replace a signature this key cannot verify: %v\n", err)
			return exitUsage
		}
		snapshot.Sequence = previous.Sequence + 1
		snapshot.Revoked = previous.Revoked
	} else if !os.IsNotExist(err) {
		return fail(err)
	}

	envelope, err := catalog.Sign(snapshot, key)
	if err != nil {
		return fail(err)
	}
	if err := envelope.Save(indexPath); err != nil {
		return fail(err)
	}
	if err := rememberPublisher(repository, *keyPath, key); err != nil {
		return fail(err)
	}

	fmt.Printf("marketplace %s\n", manifest.Name)
	fmt.Printf("signature   %s\n", indexPath)
	fmt.Printf("sequence    %d\n", snapshot.Sequence)
	fmt.Printf("signed      %d of %d plugin%s\n\n",
		len(coverage.Signed), len(manifest.Plugins), plural(len(manifest.Plugins), "", "s"))
	for _, managed := range coverage.Signed {
		fmt.Printf("  %s  %-28s %s\n", shortDigest(managed.Digest), managed.Name, managed.Version)
	}
	reportCoverage(coverage)
	fmt.Printf("\nCommit %s so machines can check what they installed.\n", CatalogFileName)
	return exitClean
}

// runMarketplacePrepareNotary writes the CI half of a hosted publish: the workflow that
// submits an already-signed catalog to the notary with the job's own OIDC token.
//
// The signing key stays on the publisher's machine. This command prepares only the
// reviewable workflow file; the first real publish is still the first accepted workflow run
// that uploads a signed non-empty catalog.
func runMarketplacePrepareNotary(args []string) int {
	flags := flag.NewFlagSet("marketplace prepare-notary", flag.ContinueOnError)
	flags.Usage = func() {
		fmt.Fprintf(flags.Output(),
			"Usage: skillctl marketplace prepare-notary [flags] [repository]\n\n"+
				"Writes a GitHub Actions workflow that submits %s to a SkillTrust notary\n"+
				"with GitHub's OIDC token, so CI stores no long-lived publish token.\n"+
				"The catalog is still signed locally: this workflow only uploads what you\n"+
				"already signed and committed.\n\n"+
				"Exit codes: %d written, %d error.\n\nFlags:\n",
			CatalogFileName, exitClean, exitUsage)
		flags.PrintDefaults()
	}

	orgName := flags.String("org", "", "organisation already registered with the notary")
	marketplaceName := flags.String("marketplace", "",
		"marketplace name at the notary; defaults to the repository's marketplace manifest name")
	branch := flags.String("branch", "main", "branch whose signed catalog should be published")
	workflow := flags.String("workflow", filepath.FromSlash(".github/workflows/notarize.yml"),
		"workflow file to write, relative to the repository unless absolute")
	notaryBase := flags.String("notary", "https://notary.axela.app",
		"SkillTrust notary base URL, for example https://notary.example.com")
	if err := parseArgs(flags, args); err != nil {
		return exitUsage
	}
	repository := flags.Arg(0)
	if repository == "" {
		repository = "."
	}
	repository, err := filepath.Abs(repository)
	if err != nil {
		return fail(err)
	}

	manifest, err := marketplace.Load(repository)
	if err != nil {
		return fail(err)
	}

	org := strings.TrimSpace(*orgName)
	if !catalogNameOK.MatchString(org) {
		fmt.Fprintln(flags.Output(),
			"skillctl: --org is required and must match the hosted notary name rules")
		return exitUsage
	}

	marketplaceID := strings.TrimSpace(*marketplaceName)
	if marketplaceID == "" {
		marketplaceID = manifest.Name
	}
	if !catalogNameOK.MatchString(marketplaceID) {
		fmt.Fprintf(flags.Output(),
			"skillctl: marketplace name %q is not usable at the notary; pass --marketplace explicitly\n",
			marketplaceID)
		return exitUsage
	}

	branchName, err := workflowBranch(*branch)
	if err != nil {
		fmt.Fprintf(flags.Output(), "skillctl: %v\n", err)
		return exitUsage
	}

	catalogURL, err := notaryCatalogURL(*notaryBase, org, marketplaceID)
	if err != nil {
		return fail(err)
	}
	workflowPath := *workflow
	if !filepath.IsAbs(workflowPath) {
		workflowPath = filepath.Join(repository, workflowPath)
	}

	content := marketplaceWorkflow(workflowActionRef(), branchName, catalogURL)
	changed, err := writeGeneratedWorkflow(workflowPath, content)
	if err != nil {
		return fail(err)
	}

	fmt.Printf("marketplace %s\n", manifest.Name)
	fmt.Printf("workflow    %s\n", workflowPath)
	if changed {
		fmt.Printf("status      written\n")
	} else {
		fmt.Printf("status      already up to date\n")
	}
	fmt.Printf("catalog     %s\n\n", catalogURL)
	fmt.Printf("Next:\n")
	fmt.Printf("  1. Run `skillctl marketplace sign %s`.\n", repository)
	fmt.Printf("  2. Review the diff, then commit %s and %s.\n",
		CatalogFileName, displayWorkflowPath(repository, workflowPath))
	fmt.Printf("  3. Push that commit to GitHub so GitHub Actions can run. " +
		"Writing this workflow prepares the route only; the first real publish is " +
		"the first accepted non-empty catalog that job uploads.\n")
	return exitClean
}

func workflowActionRef() string {
	switch {
	case strings.TrimSpace(version) != "" && strings.TrimSpace(version) != "dev":
		return "v" + strings.TrimPrefix(strings.TrimSpace(version), "v")
	case strings.TrimSpace(commit) != "":
		return strings.TrimSpace(commit)
	default:
		return "main"
	}
}

func workflowBranch(raw string) (string, error) {
	branch := strings.TrimSpace(raw)
	if branch == "" {
		return "", fmt.Errorf("--branch cannot be empty")
	}
	if strings.HasPrefix(branch, "refs/") {
		return "", fmt.Errorf("--branch must be a branch name like main or release/1.0, not %q", branch)
	}
	if branch == "@" ||
		strings.HasPrefix(branch, "-") ||
		strings.HasPrefix(branch, "/") ||
		strings.HasSuffix(branch, "/") ||
		strings.Contains(branch, "//") ||
		strings.Contains(branch, "..") ||
		strings.Contains(branch, "@{") ||
		strings.ContainsAny(branch, " \t\r\n\x00~^:?*[\\") {
		return "", fmt.Errorf("--branch must be a valid git branch name, got %q", branch)
	}
	for _, part := range strings.Split(branch, "/") {
		if part == "" ||
			strings.HasPrefix(part, ".") ||
			strings.HasSuffix(part, ".") ||
			strings.HasSuffix(part, ".lock") {
			return "", fmt.Errorf("--branch must be a valid git branch name, got %q", branch)
		}
	}
	return branch, nil
}

func notaryCatalogURL(base, org, marketplace string) (string, error) {
	origin, err := enrollment.BaseURL(strings.TrimSpace(base))
	if err != nil {
		return "", err
	}
	return origin + "/v1/catalogs/" + org + "/" + marketplace, nil
}

func marketplaceWorkflow(actionRef, branch, catalogURL string) string {
	return generatedWorkflowMarker + "\n" + fmt.Sprintf(`name: Notarize marketplace

on:
  push:
    branches:
      - %s
    paths:
      - %s
      - .github/workflows/notarize.yml
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  notarize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: %s
        with:
          command: notarize
          repository: .
          notary-url: %s
`, yamlScalar(branch), yamlScalar(CatalogFileName), yamlScalar("random1st/skilltrust@"+actionRef),
		yamlScalar(catalogURL))
}

func yamlScalar(value string) string {
	encoded, err := json.Marshal(value)
	if err != nil {
		return `""`
	}
	return string(encoded)
}

func writeGeneratedWorkflow(path, contents string) (bool, error) {
	if existing, err := os.ReadFile(path); err == nil {
		current := string(existing)
		if current == contents {
			return false, nil
		}
		if !strings.Contains(current, generatedWorkflowMarker) {
			return false, fmt.Errorf("%s already exists and was not generated here; refusing to overwrite a workflow somebody wrote", path)
		}
	} else if !os.IsNotExist(err) {
		return false, err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, err
	}
	if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
		return false, err
	}
	return true, nil
}

func displayWorkflowPath(repository, workflowPath string) string {
	if shown, err := filepath.Rel(repository, workflowPath); err == nil && shown != "" && shown != "." {
		return filepath.ToSlash(shown)
	}
	return workflowPath
}

// reportCoverage names what a signature does not cover, on the screen rather than in a
// footnote. A publisher who believes they signed 169 plugins when they signed 49 has been
// misled by their own tool.
func reportCoverage(coverage *marketplace.Coverage) {
	if len(coverage.Partial) > 0 {
		fmt.Printf("\n  partially covered — dependency code was installed after fetch and is\n")
		fmt.Printf("  outside the signature; vendor dependencies for full coverage:\n")
		for _, name := range coverage.Partial {
			fmt.Printf("    %s\n", name)
		}
	}
	if len(coverage.Unversioned) > 0 {
		fmt.Printf("\n  not signed — no version, so the installed directory cannot be named:\n")
		for _, name := range coverage.Unversioned {
			fmt.Printf("    %s\n", name)
		}
	}
	for kind, names := range coverage.Remote {
		fmt.Printf("\n  not signed — %d plugin%s hosted elsewhere (%s); this publisher does\n",
			len(names), plural(len(names), "", "s"), kind)
		fmt.Printf("  not control those bytes and cannot vouch for them\n")
	}
}

// installedStatus is the verdict for one plugin the marketplace signed.
type installedStatus struct {
	name, version, expected, actual, detail string
	ok                                      bool
}

// runMarketplaceVerify checks what Claude Code actually installed against what was signed.
//
// The plugin cache is the artifact that matters and the one nobody looks at twice: Claude
// Code copies a plugin there at install time and never returns to it, while an agent with
// write access can edit it at any point afterwards. Verifying the marketplace repository
// instead would check bytes nobody runs.
func runMarketplaceVerify(args []string) int {
	flags := flag.NewFlagSet("marketplace verify", flag.ContinueOnError)
	flags.Usage = func() {
		fmt.Fprintf(flags.Output(), "Usage: skillctl marketplace verify [flags]\n\n"+
			"Compares the plugins Claude Code installed against the marketplace signature.\n"+
			"Reads %s from the marketplace checkout and the installed copies from the\n"+
			"plugin cache.\n\n"+
			"Exit codes: %d as signed, %d something differs, %d error.\n\nFlags:\n",
			CatalogFileName, exitClean, exitFindings, exitUsage)
		flags.PrintDefaults()
	}

	repo := flags.String("repo", "", "marketplace checkout to read the signature from")
	keyPath := flags.String("key", "", "public key the signature must carry (required with --repo)")
	claudeHome := flags.String("claude-home", "", "Claude Code directory (default ~/.claude)")
	restore := flags.Bool("restore", false,
		"put changed plugins back to what was signed, keeping the replaced copy")

	if err := parseArgs(flags, args); err != nil {
		return exitUsage
	}
	home := *claudeHome
	if home == "" {
		home = marketplace.DefaultClaudeHome()
	}

	snapshots, code := marketplaceSnapshots(*repo, *keyPath)
	if code != exitClean {
		return code
	}

	sources := marketplaceSources(*repo)
	now := time.Now().UTC()
	problems, restored := 0, 0

	// This is the fourth surface that can put bytes back, and it must honour adoptions
	// like the other three — a manual verify that quietly reverts a copy its owner chose
	// to keep closes the escape hatch behind exactly the person checking their machine.
	adopted, err := marketplace.LoadAdoptions(defaultAdoptions())
	if err != nil {
		fmt.Fprintf(os.Stderr, "skillctl: %v\n  Nothing is adopted this run, so every "+
			"signed skill is checked as published.\n", err)
		adopted = marketplace.Adoptions{}
	}

	for name, snapshot := range snapshots {
		fmt.Printf("%s   sequence %d\n", name, snapshot.Sequence)
		for _, managed := range snapshot.Skills {
			status := checkInstalled(home, name, managed, snapshot)
			if status.ok {
				fmt.Printf("  ok          %-28s %s\n", status.name, status.version)
				continue
			}

			if status.detail == "changed" {
				if adoption, ok := adopted.Find(name, managed.Name); ok &&
					adoption.Local == status.actual && adoption.From == managed.Digest {
					fmt.Printf("  adapted     %-28s %s\n", status.name, adoption.Reason)
					continue
				}
			}

			// Only a changed plugin can be put back. A revoked one has no correct bytes to
			// restore, and a wrong version is a decision about which release to run rather
			// than a difference to correct.
			if *restore && status.detail == "changed" {
				kept, err := restorePlugin(sources[name], home, name, managed, now)
				if err == nil {
					restored++
					fmt.Printf("  restored    %-28s %s\n", status.name, status.version)
					fmt.Printf("              was      %s\n", status.actual)
					if kept != "" {
						fmt.Printf("              kept at  %s\n", kept)
					}
					continue
				}
				fmt.Printf("  %-11s %-28s %v\n", "unrestored", status.name, err)
				problems++
				continue
			}

			problems++
			fmt.Printf("  %-11s %-28s %s\n", status.detail, status.name, status.version)
			if status.expected != "" && status.actual != "" {
				fmt.Printf("              signed   %s\n", status.expected)
				fmt.Printf("              on disk  %s\n", status.actual)
			}
		}
		fmt.Println()
	}

	if restored > 0 {
		fmt.Printf("%d plugin%s put back to what was signed.\n",
			restored, plural(restored, "", "s"))
	}

	if problems > 0 {
		fmt.Printf("%d plugin%s %s from what was signed.\n",
			problems, plural(problems, "", "s"), plural(problems, "differs", "differ"))
		return exitFindings
	}
	if restored > 0 {
		return exitFindings
	}
	fmt.Printf("Every signed plugin is installed as signed.\n")
	return exitClean
}

// restorePlugin puts one plugin back from the marketplace checkout that signed it.
func restorePlugin(
	source, claudeHome, marketplaceName string, managed catalog.Managed, now time.Time,
) (string, error) {
	if source == "" {
		return "", fmt.Errorf("no local checkout of %s to restore from; run `skillctl sync`",
			marketplaceName)
	}
	manifest, err := marketplace.Load(source)
	if err != nil {
		return "", err
	}
	for _, entry := range manifest.Plugins {
		if entry.Name != managed.Name {
			continue
		}
		directory, local := entry.LocalPath(source)
		if !local {
			return "", fmt.Errorf("%s is hosted elsewhere, so there are no signed bytes "+
				"here to restore from", managed.Name)
		}
		installed := marketplace.InstalledPath(
			claudeHome, marketplaceName, managed.Name, managed.Version)
		return marketplace.RestoreVerified(
			installed, directory, quarantineRoot(), managed.Name, now, managed.Digest)
	}
	return "", fmt.Errorf("%s is signed but no longer listed by the marketplace", managed.Name)
}

// marketplaceSources maps each followed marketplace to the checkout its signature came from.
func marketplaceSources(explicit string) map[string]string {
	if explicit != "" {
		if manifest, err := marketplace.Load(explicit); err == nil {
			return map[string]string{manifest.Name: explicit}
		}
		return nil
	}
	subscriptions, err := loadSubscriptions()
	if err != nil {
		return nil
	}
	sources := map[string]string{}
	for _, subscription := range subscriptions {
		sources[subscription.Name] = source.Path(catalogRoot(), subscription.Name)
	}
	return sources
}

// checkInstalled compares one installed plugin against its signature.
func checkInstalled(
	claudeHome, marketplaceName string, managed catalog.Managed, snapshot *catalog.Snapshot,
) installedStatus {
	status := installedStatus{name: managed.Name, version: managed.Version, expected: managed.Digest}

	if entry, revoked := snapshot.IsRevoked(managed.Digest); revoked {
		status.detail = "revoked"
		if entry.Reason != "" {
			status.detail = "revoked"
			status.name = managed.Name + " — " + entry.Reason
		}
		return status
	}

	directory := marketplace.InstalledPath(claudeHome, marketplaceName, managed.Name, managed.Version)
	if _, err := os.Stat(directory); os.IsNotExist(err) {
		// Not installed is not drift. Reporting it as a problem would make every machine
		// that chose a subset of the catalog look compromised.
		if others := marketplace.InstalledVersions(claudeHome, marketplaceName, managed.Name); len(others) > 0 {
			status.detail = "wrong ver"
			status.version = managed.Version + " signed, " + others[0] + " installed"
			return status
		}
		status.ok = true
		status.version = managed.Version + " (not installed)"
		return status
	}

	digest, _, err := marketplace.DigestInstalled(directory)
	if err != nil {
		status.detail = "unreadable"
		return status
	}
	status.actual = digest
	// The bytes on disk can be revoked even when the published ones are not — a machine
	// running an edited copy whose digest the catalog withdrew must hear about it.
	if entry, revoked := snapshot.IsRevoked(digest); revoked {
		status.detail = "revoked"
		if entry.Reason != "" {
			status.name = managed.Name + " — " + entry.Reason
		}
		return status
	}
	if digest == managed.Digest {
		status.ok = true
		return status
	}
	status.detail = "changed"
	return status
}

// marketplaceSnapshots resolves which signatures to check, from an explicit checkout or from
// the catalogs this machine follows.
func marketplaceSnapshots(repo, keyPath string) (map[string]*catalog.Snapshot, int) {
	snapshots := map[string]*catalog.Snapshot{}

	if repo != "" {
		if keyPath == "" {
			fmt.Fprintln(os.Stderr, "skillctl: --repo needs --key; a signature checked "+
				"against no particular key is not a check")
			return nil, exitUsage
		}
		public, err := attest.LoadPublicKey(keyPath)
		if err != nil {
			return nil, fail(err)
		}
		envelope, err := attest.LoadEnvelope(filepath.Join(repo, CatalogFileName))
		if err != nil {
			return nil, fail(err)
		}
		snapshot, _, err := catalog.Verify(envelope,
			attest.NewTrustedKeys(public), nil, time.Now().UTC())
		if err != nil {
			fmt.Fprintf(os.Stderr, "skillctl: the signature did not verify: %v\n", err)
			return nil, exitFindings
		}
		snapshots[snapshot.Name] = snapshot
		return snapshots, exitClean
	}

	subscriptions, err := loadSubscriptions()
	if err != nil {
		return nil, fail(err)
	}
	if len(subscriptions) == 0 {
		fmt.Fprintln(os.Stderr, "skillctl: no marketplaces followed; pass --repo and --key, "+
			"or subscribe with `skillctl subscribe <git-url> --key <publisher.pub>`")
		return nil, exitUsage
	}
	trusted, err := attest.LoadTrustedKeys(defaultTrustedKeys())
	if err != nil {
		return nil, fail(err)
	}
	now := time.Now().UTC()
	for _, subscription := range subscriptions {
		snapshot, err := readSnapshotOnly(subscription, trusted, now)
		if err != nil {
			fmt.Fprintf(os.Stderr, "skillctl: %s could not be verified: %v\n",
				subscription.Name, err)
			return nil, exitFindings
		}
		snapshots[snapshot.Name] = snapshot
	}
	return snapshots, exitClean
}

// runMarketplaceCountersign adds a signature to an index another key already signed.
//
// This is the second half of a threshold, and it is a separate command because it is a
// separate act: signing says these are the bytes I publish, countersigning says I have looked
// at what you published and agree. Folding it into `sign` would let one person do both from
// one machine, which is the arrangement a threshold exists to prevent.
//
// The payload is never re-serialized. Both signatures cover the same bytes, so a verifier is
// comparing agreement about one document rather than two encodings of it.
func runMarketplaceCountersign(args []string) int {
	flags := flag.NewFlagSet("marketplace countersign", flag.ContinueOnError)
	flags.Usage = func() {
		fmt.Fprintf(flags.Output(),
			"Usage: skillctl marketplace countersign [flags] [repository]\n\n"+
				"Adds your signature to %s without changing what it says. Verify what it\n"+
				"covers first: countersigning is agreement, not a formality.\n\n"+
				"Exit codes: %d signed, %d error.\n\nFlags:\n",
			CatalogFileName, exitClean, exitUsage)
		flags.PrintDefaults()
	}

	keyPath := flags.String("key", defaultSigningKey(), "your signing key")
	expect := flags.String("expect-sequence", "",
		"refuse unless the index is at this sequence, so a republish cannot slip past review")

	if err := parseArgs(flags, args); err != nil {
		return exitUsage
	}
	repository := flags.Arg(0)
	if repository == "" {
		repository = "."
	}
	repository, err := filepath.Abs(repository)
	if err != nil {
		return fail(err)
	}

	indexPath := filepath.Join(repository, CatalogFileName)
	envelope, err := attest.LoadEnvelope(indexPath)
	if err != nil {
		return fail(err)
	}

	// Read what is being agreed to, without verifying against any particular key: the point
	// here is to show the reviewer the contents, and their own signature is the assertion.
	payload, err := envelope.DecodedPayload()
	if err != nil {
		return fail(err)
	}
	var snapshot catalog.Snapshot
	if err := json.Unmarshal(payload, &snapshot); err != nil {
		return fail(err)
	}
	if *expect != "" && *expect != fmt.Sprint(snapshot.Sequence) {
		fmt.Fprintf(os.Stderr, "skillctl: the index is at sequence %d, not %s; refusing to "+
			"sign something other than what you reviewed\n", snapshot.Sequence, *expect)
		return exitUsage
	}

	key, err := attest.LoadPrivateKey(*keyPath)
	if err != nil {
		return fail(err)
	}
	if err := attest.Countersign(envelope, key); err != nil {
		return fail(err)
	}
	if err := envelope.Save(indexPath); err != nil {
		return fail(err)
	}

	fmt.Printf("marketplace %s\n", snapshot.Name)
	fmt.Printf("sequence    %d\n", snapshot.Sequence)
	fmt.Printf("covers      %d plugin%s\n", len(snapshot.Skills),
		plural(len(snapshot.Skills), "", "s"))
	fmt.Printf("signatures  %d\n\n", len(envelope.Signatures))
	for _, managed := range snapshot.Skills {
		fmt.Printf("  %s  %-28s %s\n", shortDigest(managed.Digest), managed.Name, managed.Version)
	}
	fmt.Printf("\nCommit %s.\n", CatalogFileName)
	return exitClean
}
