package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Raw values keep settings outside this proposal intact, including numbers too large for
// float64. Only the small set of settings generated by policy is merged here.
type policyObject map[string]json.RawMessage

type policyChange struct {
	path          string
	before, after json.RawMessage
}

func previewManagedPolicy(from, out string, diff bool, name, repo, plugin string, requested map[string]any) int {
	raw, err := os.ReadFile(from)
	if err != nil {
		return fail(err)
	}
	settings, changes, err := mergeManagedPolicy(raw, name, repo, plugin, requested)
	if err != nil {
		return fail(err)
	}
	body, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		return fail(err)
	}
	body = append(body, '\n')
	if out != "" {
		if err := writePolicyProposal(out, body, filepath.Dir(managedSettingsPath())); err != nil {
			return fail(err)
		}
	}
	if diff {
		writePolicyDiff(from, changes)
	} else if out == "" {
		fmt.Printf("%s\n", body)
	}
	if out != "" {
		fmt.Printf("Proposal saved to %s\n\n", out)
	}
	writePolicyNextSteps()
	return exitClean
}

func mergeManagedPolicy(raw []byte, name, repo, plugin string, requested map[string]any) (policyObject, []policyChange, error) {
	document, err := decodePolicyObject(raw, "exported policy")
	if err != nil {
		return nil, nil, err
	}
	encoded, err := json.Marshal(requested)
	if err != nil {
		return nil, nil, err
	}
	want, err := decodePolicyObject(encoded, "proposed policy")
	if err != nil {
		return nil, nil, err
	}
	var changes []policyChange

	// An existing allowlist is an organisation's decision. Never append a source to it or
	// drop its other entries to make this proposal appear compatible. The generated source
	// is an unqualified GitHub repository; ref/path variants are different sources in Claude.
	if existing, present := document["strictKnownMarketplaces"]; present {
		var entries []json.RawMessage
		if err := json.Unmarshal(existing, &entries); err != nil || entries == nil {
			return nil, nil, fmt.Errorf("strictKnownMarketplaces must be an array of sources")
		}
		allowed := false
		for _, entry := range entries {
			source, err := decodePolicyObject(entry, "strictKnownMarketplaces source")
			if err != nil {
				return nil, nil, err
			}
			var kind string
			if err := json.Unmarshal(source["source"], &kind); err != nil || kind == "" {
				return nil, nil, fmt.Errorf("strictKnownMarketplaces entry must name a source type")
			}
			if exactPolicyGithubSource(entry, repo) {
				allowed = true
			}
		}
		if !allowed {
			return nil, nil, fmt.Errorf("cannot confirm %q is allowed: strictKnownMarketplaces has no exact, unqualified GitHub source for it; ask the MDM owner to review the restriction (patterns are not evaluated by this preview); the allowlist was not changed", repo)
		}
		if _, lockdown := want["strictKnownMarketplaces"]; lockdown && len(entries) != 1 {
			return nil, nil, fmt.Errorf("--lockdown would replace the existing strictKnownMarketplaces allowlist; ask the MDM owner to review that change separately")
		}
	} else if strict, lockdown := want["strictKnownMarketplaces"]; lockdown {
		document["strictKnownMarketplaces"] = strict
		changes = append(changes, policyChange{path: "/strictKnownMarketplaces", after: strict})
	}

	marketplaces, err := policySection(document, "extraKnownMarketplaces")
	if err != nil {
		return nil, nil, err
	}
	if existing, present := marketplaces[name]; present {
		entry, err := decodePolicyObject(existing, "extraKnownMarketplaces entry")
		if err != nil {
			return nil, nil, err
		}
		if !exactPolicyGithubSource(entry["source"], repo) {
			return nil, nil, fmt.Errorf("extraKnownMarketplaces[%q] already has a different or qualified source; ask the MDM owner to resolve the source conflict", name)
		}
	} else {
		additions, err := policySection(want, "extraKnownMarketplaces")
		if err != nil {
			return nil, nil, err
		}
		marketplaces[name] = additions[name]
		changes = append(changes, policyChange{path: "/extraKnownMarketplaces/" + policyPointer(name), after: additions[name]})
	}
	if document["extraKnownMarketplaces"], err = json.Marshal(marketplaces); err != nil {
		return nil, nil, err
	}

	plugins, err := policySection(document, "enabledPlugins")
	if err != nil {
		return nil, nil, err
	}
	pluginID := plugin + "@" + name
	if bytes.Equal(bytes.TrimSpace(plugins[pluginID]), []byte("false")) {
		return nil, nil, fmt.Errorf("enabledPlugins[%q] is explicitly disabled; ask the MDM owner to approve enabling it", pluginID)
	}
	if err := enablePolicyField(plugins, pluginID, "/enabledPlugins/"+policyPointer(pluginID), &changes); err != nil {
		return nil, nil, err
	}
	if document["enabledPlugins"], err = json.Marshal(plugins); err != nil {
		return nil, nil, err
	}

	customization, err := policySection(document, "strictPluginOnlyCustomization")
	if err != nil {
		return nil, nil, err
	}
	for _, key := range []string{"skills", "agents", "hooks", "mcp"} {
		if err := enablePolicyField(customization, key, "/strictPluginOnlyCustomization/"+key, &changes); err != nil {
			return nil, nil, err
		}
	}
	if document["strictPluginOnlyCustomization"], err = json.Marshal(customization); err != nil {
		return nil, nil, err
	}
	for _, key := range []string{"allowManagedHooksOnly", "disableSideloadFlags", "disableCommandPluginSources"} {
		if err := enablePolicyField(document, key, "/"+key, &changes); err != nil {
			return nil, nil, err
		}
	}
	sort.Slice(changes, func(i, j int) bool { return changes[i].path < changes[j].path })
	return document, changes, nil
}

func exactPolicyGithubSource(raw json.RawMessage, repo string) bool {
	source, err := decodePolicyObject(raw, "marketplace source")
	if err != nil || len(source) != 2 {
		return false
	}
	var kind, repository string
	return json.Unmarshal(source["source"], &kind) == nil && kind == "github" &&
		json.Unmarshal(source["repo"], &repository) == nil && repository == repo
}

func policySection(document policyObject, key string) (policyObject, error) {
	if raw, present := document[key]; present {
		return decodePolicyObject(raw, key)
	}
	return policyObject{}, nil
}

func enablePolicyField(document policyObject, key, path string, changes *[]policyChange) error {
	before, present := document[key]
	if present {
		switch string(bytes.TrimSpace(before)) {
		case "true":
			return nil
		case "false":
		default:
			return fmt.Errorf("%s must be a boolean; ask the MDM owner to review its existing value", path)
		}
	}
	after := json.RawMessage("true")
	document[key] = after
	*changes = append(*changes, policyChange{path: path, before: before, after: after})
	return nil
}

// Reject duplicate keys in every object we rewrite. Silently choosing the last value
// could discard a restriction or an unknown setting from an exported policy.
func decodePolicyObject(raw []byte, where string) (policyObject, error) {
	decoder := json.NewDecoder(bytes.NewReader(raw))
	token, err := decoder.Token()
	if err != nil || token != json.Delim('{') {
		return nil, fmt.Errorf("%s must be a JSON object", where)
	}
	object := policyObject{}
	for decoder.More() {
		token, err := decoder.Token()
		if err != nil {
			return nil, fmt.Errorf("%s is not valid JSON: %w", where, err)
		}
		key, ok := token.(string)
		if !ok {
			return nil, fmt.Errorf("%s has a non-string key", where)
		}
		if _, duplicate := object[key]; duplicate {
			return nil, fmt.Errorf("%s repeats key %q; ask the MDM owner to resolve the ambiguity", where, key)
		}
		var value json.RawMessage
		if err := decoder.Decode(&value); err != nil {
			return nil, fmt.Errorf("%s is not valid JSON: %w", where, err)
		}
		object[key] = value
	}
	if _, err := decoder.Token(); err != nil {
		return nil, fmt.Errorf("%s is not valid JSON: %w", where, err)
	}
	if _, err := decoder.Token(); err != io.EOF {
		return nil, fmt.Errorf("%s must contain one JSON object", where)
	}
	return object, nil
}

func policyPointer(key string) string {
	return strings.NewReplacer("~", "~0", "/", "~1").Replace(key)
}

func writePolicyDiff(from string, changes []policyChange) {
	if len(changes) == 0 {
		fmt.Println("No policy changes needed.")
		return
	}
	fmt.Printf("Policy changes from %q (JSON paths):\n", from)
	for _, change := range changes {
		fmt.Printf("@@ %q @@\n", change.path)
		for _, side := range []struct {
			prefix string
			value  json.RawMessage
		}{{"-", change.before}, {"+", change.after}} {
			if len(side.value) == 0 {
				continue
			}
			var formatted bytes.Buffer
			_ = json.Indent(&formatted, side.value, "", "  ") // values were decoded above
			for _, line := range strings.Split(formatted.String(), "\n") {
				fmt.Printf("%s %s\n", side.prefix, line)
			}
		}
	}
	fmt.Println()
}

func writePolicyProposal(path string, body []byte, managed string) error {
	absolute, err := filepath.Abs(path)
	if err != nil {
		return err
	}
	parent, err := filepath.EvalSymlinks(filepath.Dir(absolute))
	if err != nil {
		return err
	}
	if resolved, err := filepath.EvalSymlinks(managed); err == nil {
		managed = resolved
	}
	relative, err := filepath.Rel(managed, filepath.Join(parent, filepath.Base(absolute)))
	insideManaged := err == nil && relative != ".." && !strings.HasPrefix(relative, ".."+string(filepath.Separator))
	// Directory identity also catches case aliases on case-insensitive filesystems.
	if protected, err := os.Stat(managed); err == nil {
		for ancestor := parent; !insideManaged; ancestor = filepath.Dir(ancestor) {
			if info, err := os.Stat(ancestor); err == nil && os.SameFile(info, protected) {
				insideManaged = true
			}
			if filepath.Dir(ancestor) == ancestor {
				break
			}
		}
	}
	if insideManaged {
		return fmt.Errorf("--out must be a new proposal outside the system managed-settings directory; give it to the MDM owner for review")
	}
	// O_EXCL also refuses symlinks and hardlinks to the source, without a check-then-write
	// race that could overwrite an existing export. An export may contain private settings.
	file, err := os.OpenFile(path, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0o600)
	if err != nil {
		return fmt.Errorf("cannot create proposal %q: %w; choose a new output path, existing files are never overwritten with --from", path, err)
	}
	if _, err := file.Write(body); err != nil {
		_ = file.Close()
		return err
	}
	return file.Close()
}
