// Package notary answers one question about one skill: were these bytes approved by someone
// this machine trusts, and does that approval still stand.
//
// It is the whole trust path. Everything else — a lockfile, an install receipt, a note that
// something was fetched from a repository — records history, and history is not approval. A
// record that can be regenerated by whoever edited the skill cannot be evidence about the
// skill, so those records are deliberately not consulted here.
package notary

import (
	"crypto/ed25519"
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"github.com/random1st/skilltrust/client/internal/archive"
	"github.com/random1st/skilltrust/client/internal/attest"
	"github.com/random1st/skilltrust/client/internal/catalog"
	"github.com/random1st/skilltrust/client/internal/skillmd"
)

// Status is the verdict for one skill.
//
// The failures are kept apart rather than collapsed into "not verified" because they call
// for different actions: an unsigned skill needs signing, an untrusted one needs a decision
// about a publisher, a mismatched one means the bytes moved, and a revoked one must be
// removed no matter how good its signature is.
type Status string

const (
	// StatusVerified is the only passing verdict.
	StatusVerified Status = "verified"
	// StatusUnsigned means no attestation was found in the skill.
	StatusUnsigned Status = "unsigned"
	// StatusUntrusted means a valid signature by a key this machine does not pin.
	StatusUntrusted Status = "untrusted"
	// StatusMismatched means the attestation covers different bytes than the ones present.
	StatusMismatched Status = "mismatched"
	// StatusInvalid means the envelope is malformed or its signature does not check out.
	StatusInvalid Status = "invalid"
	// StatusRevoked means the digest is in the revocation catalog. It outranks a good
	// signature: revocation is a statement about now, and a signature is a statement about
	// the past.
	StatusRevoked Status = "revoked"
	// StatusUnreadable means the skill could not be digested, so no claim can be made.
	StatusUnreadable Status = "unreadable"
	// StatusUnknown means revocation could not be checked, so nothing can be concluded.
	StatusUnknown Status = "unknown"
)

// OK reports whether the verdict permits use.
func (s Status) OK() bool { return s == StatusVerified }

// Result is what a check found.
type Result struct {
	Name       string `json:"name,omitempty"`
	Directory  string `json:"directory"`
	Status     Status `json:"status"`
	Digest     string `json:"digest,omitempty"`
	Expected   string `json:"expected,omitempty"`
	ApprovedBy string `json:"approved_by,omitempty"`
	KeyID      string `json:"key_id,omitempty"`
	Detail     string `json:"detail,omitempty"`
}

// Path is where a skill's own attestation lives.
func Path(directory string) string {
	return filepath.Join(directory, archive.AttestationFileName)
}

// Check runs the verification algorithm against one skill directory.
//
// A nil snapshot means no revocation catalog is configured. That is reported as unknown
// rather than passed over: "we did not check whether this was revoked" and "this was not
// revoked" are different facts, and only one of them is safe to act on.
func Check(directory string, trusted *attest.TrustedKeys, snapshot *catalog.Snapshot) Result {
	result := Result{Directory: directory}
	result.Name, _ = skillmd.Parse(filepath.Join(directory, skillmd.FileName)).Name()

	built, err := archive.Build(directory, archive.Limits{})
	if err != nil {
		result.Status, result.Detail = StatusUnreadable, err.Error()
		return result
	}
	result.Digest = built.Digest

	// Revocation first. A revoked digest is refused whatever its signature says, and
	// checking it before the signature means a revoked skill cannot be reported as merely
	// unsigned when its envelope is also missing.
	if snapshot == nil {
		result.Status = StatusUnknown
		result.Detail = "no revocation catalog is configured, so it is not known whether " +
			"these bytes have been revoked"
		return result
	}
	if entry, revoked := snapshot.IsRevoked(built.Digest); revoked {
		result.Status, result.Detail = StatusRevoked, entry.Reason
		return result
	}

	envelope, err := attest.LoadEnvelope(Path(directory))
	if errors.Is(err, os.ErrNotExist) {
		result.Status = StatusUnsigned
		result.Detail = "no " + archive.AttestationFileName + " in the skill"
		return result
	}
	if err != nil {
		result.Status, result.Detail = StatusInvalid, err.Error()
		return result
	}

	statement, keyID, err := attest.Verify(envelope, trusted)
	switch {
	case errors.Is(err, attest.ErrUntrustedKey):
		result.Status = StatusUntrusted
		result.Detail = "signed by a key this machine does not pin; import it deliberately " +
			"with --trust-key if you mean to trust this publisher"
		return result
	case err != nil:
		result.Status, result.Detail = StatusInvalid, err.Error()
		return result
	}

	result.ApprovedBy, result.KeyID = statement.ApprovedBy, keyID

	if statement.Subject.Digest != built.Digest {
		result.Status = StatusMismatched
		result.Expected = statement.Subject.Digest
		result.Detail = "the approval covers different bytes than the ones on disk"
		return result
	}
	// The name is checked too: an envelope lifted from one skill and dropped into another
	// would otherwise verify, since the digest travels with the bytes it was copied from.
	if result.Name != "" && statement.Subject.Name != "" &&
		statement.Subject.Name != result.Name {
		result.Status = StatusMismatched
		result.Detail = fmt.Sprintf("the approval is for %q but this skill declares %q",
			statement.Subject.Name, result.Name)
		return result
	}

	result.Status = StatusVerified
	return result
}

// Sign writes an attestation into the skill it describes and returns the digest it covers.
func Sign(directory string, statement attest.Statement, key ed25519.PrivateKey) (string, error) {
	built, err := archive.Build(directory, archive.Limits{})
	if err != nil {
		return "", err
	}
	statement.Version = attest.StatementVersion
	statement.Subject.Digest = built.Digest
	if statement.Subject.Name == "" {
		statement.Subject.Name, _ = skillmd.Parse(
			filepath.Join(directory, skillmd.FileName)).Name()
	}

	envelope, _, err := attest.Sign(statement, key)
	if err != nil {
		return "", err
	}
	if err := envelope.Save(Path(directory)); err != nil {
		return "", err
	}
	return built.Digest, nil
}
